version: 2
jobs:
  deploy-staging:
    working_directory: ~/docs
    docker:
      - image: circleci/ruby:2.3.3
        environment:
          BUNDLE_PATH: vendor/bundle
          BUNDLER_VERSION: 2.0.2
          TZ: /usr/share/zoneinfo/Asia/Tokyo

    steps:
      - checkout
      - run:
          name: installing pyenv
          command: |
            unset PYENV_ROOT
            curl https://pyenv.run | bash
            export PATH="$HOME/.pyenv/bin:$PATH"
            pyenv update
            pyenv install 3.5.2
      - run:
          name: install aws cli
          command: |
            pip3 install awscli --upgrade --user
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy-staging:
          filters:
            branches:
              only: master
