version: 2
jobs:
  deploy-staging:
    working_directory: ~/docs
    docker:
      - image: circleci/ruby:2.3.3
        environment:
          BUNDLE_PATH: vendor/bundle
          BUNDLER_VERSION: 2.0.2
          TZ: /usr/share/zoneinfo/Asia/Tokyo

    steps:
      - checkout
      - run:
          name: installing pyenv
          command: |
            unset PYENV_ROOT
            curl https://pyenv.run | bash
            export PATH="$HOME/.pyenv/bin:$PATH"
            echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> ~/.bashrc
            echo 'eval "$(pyenv init -)"' >> ~/.bashrc
            echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bashrc
            source ~/.bashrc
            pyenv update
            pyenv install 3.5.2
            pip install awscli --upgrade --user
      - run:
          name: installing aws cli1
          command: |
            source ~/.bashrc
            which pip
      - run:
          name: installing aws cli2
          command: |
            source ~/.bashrc
            which pip
            pip install awscli --upgrade --user
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy-staging:
          filters:
            branches:
              only: master
